---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-railroad
  namespace: demo-railroad
spec:
  replicas: 1
  selector:
    matchLabels:
      demo: railroad
  serviceName: demo
  template:
    metadata:
      labels:
        demo: railroad
    spec:
      containers:
        - image: DOCKER_IMAGE
          imagePullPolicy: Always
          name: demo
          ports:
            - containerPort: 9001
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "2"
              memory: 4Gi

