import { Value, ValueDownlinkFastener } from "@swim/runtime";
import { Model, ModelRef, SelectableTrait, TraitRef } from "@swim/toolkit";
import { EntityTrait, StatusFactor, WidgetGroup } from "@swim/platform";
export declare class RclWidgets extends WidgetGroup {
    protected updateStatusTable(value: Value): void;
    private getTimeStr;
    private getStatusFactorFromAlert;
    readonly statusTable: ModelRef<this, Model>;
    readonly statusWidget: ModelRef<this, Model>;
    protected updateOperationGauge(value: Value): void;
    readonly operationGauge: ModelRef<this, Model>;
    protected updateOperationTable(value: Value): void;
    getWarningStatusFromFlag(flag: boolean): StatusFactor | null;
    getAlertStatusFromFlag(flag: boolean): StatusFactor | null;
    readonly operationTable: ModelRef<this, Model>;
    readonly operationWidget: ModelRef<this, Model>;
    protected updatePerformanceGauge(value: Value): void;
    readonly performanceGauge: ModelRef<this, Model>;
    protected updatePerformanceTable(value: Value): void;
    getStatusFactorFromHighPercentage(usage: number): StatusFactor | null;
    getStatusFactorFromLowPercentage(usage: number): StatusFactor | null;
    readonly performanceTable: ModelRef<this, Model>;
    readonly performanceWidget: ModelRef<this, Model>;
    protected updateHealthTable(value: Value): void;
    readonly healthTable: ModelRef<this, Model>;
    readonly healthWidget: ModelRef<this, Model>;
    protected updateInfoTable(value: Value): void;
    readonly infoTable: ModelRef<this, Model>;
    readonly infoWidget: ModelRef<this, Model>;
    readonly statusDownlink: ValueDownlinkFastener<this, Value>;
    readonly rcuMetricsDownlink: ValueDownlinkFastener<this, Value>;
    readonly locomotiveMetricsDownlink: ValueDownlinkFastener<this, Value>;
    readonly infoDownlink: ValueDownlinkFastener<this, Value>;
    readonly selectable: TraitRef<this, SelectableTrait>;
    readonly entity: TraitRef<this, EntityTrait>;
}
